'use strict';
const assert=require('assert/strict'),fs=require('fs'),vm=require('vm'),{DEFAULTS}=require('./banko_coupon');
class E{constructor(tag='div'){this.tagName=tag;this.children=[];this.textContent='';this.className='';this.dataset={};this.value='';this.checked=false;this.disabled=false;this.hidden=false;this.attributes={};}setAttribute(k,v){this.attributes[k]=String(v);}appendChild(n){this.children.push(n);return n;}append(...nodes){nodes.forEach(n=>this.appendChild(n));}replaceChildren(...nodes){this.children=[];this.append(...nodes);}}
const nodes=new Map(),node=id=>{if(!nodes.has(id))nodes.set(id,new E());return nodes.get(id);},text=e=>[e.textContent,...e.children.map(text)].join(' ');
const pick={key:'5|Over 1.5',betId:5,selection:'Over 1.5',spec:{kind:'total',period:'full',direction:'over',line:1.5,family:'goals'},odd:1.5,modelProbability:.8,dataScore:100,edgePP:13.3,eligible:true,reasons:[]};
const rows=[['Selected late','19:00',pick],['PAS earliest','01:00',null],['Selected early','14:00',pick],['PAS later','21:00',null]].map(([match,time,p],i)=>({fixtureId:i+1,match,league:'Test',kickoff:'2099-10-05T'+time+':00Z',home:{name:'Home'},away:{name:'Away'},pick:p,markets:[],profiles:null,risks:[],reasons:[]}));
let state={date:'2099-10-05',day:'2099-10-06',settings:DEFAULTS,api:{used:20,limit:20,reserve:1500,remaining:6000},scan:{canResume:true,target:100,accepted:2,examined:4,total:6},summary:{coupons:0,candidates:4,selected:2,pas:2,won:0,lost:0,pending:0,profitUnits:0},sessions:[{id:'s',createdAt:'2099-10-05',status:'waiting-budget',couponCount:0}],availableDates:['2099-10-05'],session:{id:'s',status:'waiting-budget',createdAt:'2099-10-05',reason:'Bütçe bekleniyor',coupons:[],candidates:rows},busy:false,storageError:null,job:{id:'j',status:'waiting-budget',message:'Bütçe bekleniyor'}};
const requests=[],context={window:{},document:{getElementById:node,createElement:t=>new E(t),querySelectorAll:()=>[]},Date,Intl,apiFetch:async(url,options)=>{requests.push({url,options});return state;},showToast(){}};
vm.runInNewContext(fs.readFileSync('public/banko_choices.js','utf8'),context);vm.runInNewContext(fs.readFileSync('public/banko_coupon_panel.js','utf8'),context);
(async()=>{const original=JSON.stringify(rows);node('banko-date').value=state.date;await context.window.fetchBankoCoupon();assert.equal(node('banko-resume').hidden,false);assert.equal(node('banko-resume').disabled,false);assert.match(node('banko-count').textContent,/2 tahmin.*2 PAS/);assert.match(node('banko-progress').textContent,/2\/100.*yalnız 2099-10-05/);assert(!text(node('banko-coupons')).includes('Eksik tarama kupon onayı sayılmaz'),'Quota wait is not shown as generic error');assert.match(text(node('banko-candidates').children[0]),/Selected early/);assert.match(text(node('banko-candidates').children[1]),/Selected late/);assert.equal(node('banko-candidates').children.length,2);
    const n=requests.length;node('banko-show-pas').checked=true;context.window.bankoSearch();assert.deepEqual(node('banko-candidates').children.map(n=>text(n).match(/Selected early|Selected late|PAS earliest|PAS later/)[0]),['Selected early','Selected late','PAS earliest','PAS later']);assert.equal(requests.length,n);node('banko-search').value='PAS';context.window.bankoSearch();assert.equal(node('banko-candidates').children.length,2);assert.equal(JSON.stringify(rows),original);
    await context.window.runBankoAction('resume');const post=requests.find(r=>r.url==='/api/banko-coupon/resume');assert.deepEqual(JSON.parse(post.options.body),{date:'2099-10-05',sessionId:'s'},'Resume original date/session, not today');
    state={...state,scan:{...state.scan,canResume:false,stopReason:'day-exhausted'},session:{...state.session,status:'complete'}};await context.window.fetchBankoCoupon();assert(node('banko-resume').hidden);assert.match(node('banko-progress').textContent,/Seçili gün tamamlandı.*başka güne geçilmedi/);
    state={...state,busy:true,scan:{...state.scan,canResume:true}};await context.window.fetchBankoCoupon();assert(node('banko-resume').disabled);state={...state,busy:false,storageError:'blocked'};await context.window.fetchBankoCoupon();assert(node('banko-resume').disabled);
    const html=fs.readFileSync('public/index.html','utf8');assert(html.includes('En fazla uygun ana tahmin (PAS hariç)'));assert(html.includes('DEVAM ET · AYNI TARAMA'));assert(!html.match(/<input[^>]*id="banko-show-pas"[^>]*>/)[0].includes('checked'));assert(!html.match(/<input[^>]*id="banko-strength-show-pas"[^>]*>/)[0].includes('checked'));assert.equal(html,fs.readFileSync('index.html','utf8'));
    console.log('Banko scan panel: default hidden PAS, selected-first chronological groups, local search/toggle, immutable data, target/count/date labels, quota checkpoint state and original-date/session manual resume route passed.');
})().catch(e=>{console.error(e);process.exitCode=1;});
