'use strict';
const assert=require('assert/strict'),fs=require('fs'),path=require('path'),S=require('./public/banko_showroom'),M=require('./banko_model'),{BankoCoupon,DEFAULTS}=require('./banko_coupon');
const clone=x=>JSON.parse(JSON.stringify(x)),date='2099-10-08',at='2099-10-08T08:00:00Z';
const close=(actual,expected,message)=>assert(Math.abs(actual-expected)<1e-10,message);
const pick={key:'5|Over 1.5',betId:5,selection:'Over 1.5',market:'Goals',spec:M.specFor(5,'Over 1.5'),odd:1.6,modelProbability:.8,dataScore:100,edgePP:17.5,eligible:true,reasons:[],modelVersion:M.VERSION};
const p=(games=20,scored=1.2)=>({last5:{games:Math.min(5,games),scored,conceded:.8},last20:{games,scored:1.35,conceded:1}});
const row=id=>({fixtureId:id,match:'Ev '+id+' - Dep',home:{name:'Ev '+id},away:{name:'Dep'},league:'Test',kickoff:'2099-10-08T19:00:00Z',capturedAt:at,oddsUpdatedAt:at,profiles:{home:p(),away:p()},expectedGoals:{home:1.1,away:1.3},pick:clone(pick),markets:[clone(pick)]});
const manual=(id,tag='deneme1',playedOdd=1.4)=>({id:'manual-'+id,date,sessionId:'s1',fixtureId:id,match:'Ev '+id+' - Dep',kickoff:row(id).kickoff,pick:clone(pick),tag,playedOdd,createdAt:at,priceHistory:[],timing:'prematch',result:{status:'pending'},showroomContext:S.snapshotFor(row(id))});
const entries=[manual(1),manual(2,'deneme1',1.45),manual(3,'deneme1',1.5)],before=JSON.stringify(entries);
let group=S.buildGroups(entries)[0];assert.equal(group.legs.length,3);assert(Math.abs(group.totalOdd-3.045)<1e-10);assert.equal(group.result,'pending');close(group.legs[0].context.expectedTotal,2.4);assert.equal(JSON.stringify(entries),before);
assert.equal(S.buildGroups([...entries,{...manual(4),date:'2099-10-09'}]).length,2,'Same tag on another day is separate');
assert.equal(S.buildGroups([manual(1,''),manual(2,'')]).length,2,'Empty labels never combine all selections');
assert.equal(S.buildGroups([manual(1),manual(2,' deneme1 ')]).length,1);
group=S.buildGroups([manual(1),manual(2,'deneme1',null)])[0];assert.equal(group.totalOdd,null);assert.equal(group.missingOdds,1);assert.equal(group.legs[1].playedOdd,null);assert.match(S.couponText(group),/Toplam oynanan oran: —/);assert(!S.couponText(group).includes('1.60'),'Never substitute provider odds');
for(const bad of ['',false,'1.4',0,Infinity,NaN,1001])assert.equal(S.buildGroups([manual(1,'bad',bad)])[0].totalOdd,null);
const duplicate={...manual(1),id:'duplicate',sessionId:'s2',playedOdd:1.8,createdAt:'2099-10-08T09:00:00Z'};
group=S.buildGroups([manual(1),duplicate])[0];assert.equal(group.legs.length,1);assert.equal(group.totalOdd,1.8);assert.equal(group.duplicateCount,1);
const edited={...manual(1),playedOdd:1.9,priceHistory:[{changedAt:'2099-10-08T10:00:00Z'}]};assert.equal(S.buildGroups([edited,duplicate])[0].totalOdd,1.9);
const alias={...manual(1),id:'alias',pick:{...pick,key:'10|0:0',spec:M.specFor(10,'0:0')}},zero={...manual(1),pick:{...pick,key:'5|Under 0.5',spec:M.specFor(5,'Under 0.5')}};
assert.equal(S.buildGroups([zero,alias])[0].legs.length,1);
const other={...manual(1),id:'other',pick:{...pick,key:'8|Yes',spec:M.specFor(8,'Yes')}};group=S.buildGroups([manual(1),other])[0];assert(group.sameFixture);assert.equal(group.totalOdd,null);assert.equal(group.result,'pending');
group=S.buildGroups(entries.map(e=>({...e,result:{status:'won'}})))[0];assert.equal(group.result,'won');assert(Math.abs(group.profitUnits-2.045)<1e-10);
group=S.buildGroups(entries.map((e,i)=>({...e,result:{status:i===0?'lost':'pending'}})))[0];assert.equal(group.result,'lost');assert.equal(group.profitUnits,-1);
assert.equal(S.snapshotFor(null).expectedTotal,null);assert.equal(S.snapshotFor({expectedGoals:{home:null,away:1}}).expectedTotal,null);assert.equal(S.snapshotFor({expectedGoals:{home:0,away:0}}).expectedTotal,0);
const short=S.snapshotFor({...row(1),profiles:{home:p(3,0),away:p(9)}});assert.equal(short.home.last5.scored,0);assert.equal(short.home.last5.games,3);assert.equal(S.periodLabel(short.home.last5),'Son 5 · 3 maç');
assert.equal(S.normalizeContext({home:{last5:{games:0,scored:0}}}).home.last5.scored,null);
assert.match(S.parts({...pick,spec:M.specFor(17,'Over 0.5'),selection:'Over 0.5'}).name,/DEPLASMAN/);assert.match(S.parts({...pick,spec:M.specFor(20,'Draw/Away'),selection:'Draw/Away'}).name,/İLK YARI/);
const b=new BankoCoupon({now:()=>new Date(at),apiGet:()=>{throw Error('No provider calls allowed');}});
b.data.sessions=[{id:'s1',date,status:'complete',createdAt:at,settings:clone(DEFAULTS),candidates:[row(1)],coupons:[]},{id:'s2',date,status:'complete',createdAt:at,settings:clone(DEFAULTS),candidates:[{...row(1),expectedGoals:{home:9,away:9}}],coupons:[]}];
b.data.manualSelections=[manual(1)];delete b.data.manualSelections[0].showroomContext;
const frozen=JSON.stringify(b.data);const old=b.status(date,'s2').manualSelections[0];close(old.showroomContext.expectedTotal,2.4,'Old record uses original scan, not currently selected revision');assert.equal(JSON.stringify(b.data),frozen,'Reading does not migrate or rewrite old stores');
b.data.manualSelections=[];const saved=b.addSelection({date,sessionId:'s1',fixtureId:1,marketKey:pick.key,playedOdd:1.4,tag:'new'}).selection;close(saved.showroomSnapshot.expectedTotal,2.4);
b.data.sessions[0].candidates[0].expectedGoals.home=99;close(b.status(date).manualSelections[0].showroomContext.expectedTotal,2.4,'Saved summary stays frozen');assert.equal(b.requestCount,0);
const panel=fs.readFileSync('public/banko_showroom_panel.js','utf8'),shared=fs.readFileSync('public/banko_showroom.js','utf8'),html=fs.readFileSync('index.html','utf8');
assert(!panel.includes('innerHTML'));assert(!/apiFetch|fetch\(|setInterval|telegram\.send/i.test(panel+shared));assert(!/puppeteer|html2canvas|media\.api/.test(panel+shared));
assert(html.includes('banko-showroom-section'));assert(html.indexOf('/banko_choices.js')<html.indexOf('/banko_showroom.js'));assert(html.indexOf('/banko_showroom.js')<html.indexOf('/banko_showroom_panel.js'));assert.equal(html,fs.readFileSync('public/index.html','utf8'));
const ctx={font:'',fillStyle:'',textBaseline:'',measureText:s=>({width:String(s).length*7}),fillRect(){},fillText(){}};
assert(S.drawPage(ctx,S.buildGroups(entries)[0],S.buildGroups(entries)[0].legs,0,1)>1000);assert(S.wrap(ctx,'çokuzunbirkelime',28).every(line=>line.length<=4));
assert.equal(S.crc32(new TextEncoder().encode('123456789')),0xcbf43926);
(async()=>{
    const zip=await S.zipFiles([{name:'one.png',blob:new Blob(['one'])},{name:'two.png',blob:new Blob(['two'])}]);const bytes=new Uint8Array(await zip.arrayBuffer()),v=new DataView(bytes.buffer);assert.equal(v.getUint32(0,true),0x04034b50);assert.equal(v.getUint32(bytes.length-22,true),0x06054b50);assert.equal(v.getUint16(bytes.length-14,true),2);
    fs.mkdirSync(path.join(__dirname,'test-temp'),{recursive:true});const dir=fs.mkdtempSync(path.join(__dirname,'test-temp/banko-showroom-'));const persistent=new BankoCoupon({directory:dir,now:()=>new Date(at)});persistent.data=clone(b.data);persistent.save();const reloaded=new BankoCoupon({directory:dir,now:()=>new Date(at)});reloaded.load();assert(!reloaded.storageError);close(reloaded.status(date).manualSelections[0].showroomContext.expectedTotal,2.4);
    console.log('Showroom: 3+ legs, day/tag grouping, missing real prices, equivalent revision dedupe, same-fixture conflict, combined results, original revision fallback, frozen snapshots, sparse/zero stats, pure browser export, ZIP CRC, no provider/Telegram calls and restart passed.');
})().catch(e=>{console.error(e);process.exitCode=1;});
