'use strict';
const assert=require('assert/strict'),fs=require('fs'),vm=require('vm');
class E{constructor(tag='div'){this.tagName=tag;this.children=[];this.textContent='';this.className='';this.style={};this.dataset={};this.value='';this.checked=false;this.disabled=false;this.attributes={};}setAttribute(k,v){this.attributes[k]=String(v);}appendChild(n){this.children.push(n);return n;}append(...nodes){nodes.forEach(n=>this.appendChild(n));}replaceChildren(...nodes){this.children=[];this.append(...nodes);}focus(){}select(){}}
const nodes=new Map(),node=id=>{if(!nodes.has(id))nodes.set(id,new E());return nodes.get(id);},collect=e=>[e.textContent,...e.children.map(collect)].join(' ');
const settings=require('./banko_coupon').DEFAULTS,profile={last20:{games:20,scored:1.4,conceded:1},last5:{games:5,scored:1.2,conceded:1},venueSummary:{games:10,scored:1.5,conceded:.8},stats:{'Total Shots':{games:0,mean:null},'Yellow Cards':{games:9,mean:1.63},'Red Cards':{games:2,mean:0},expected_goals:{games:0,mean:null}},rows:[],players:[]};
const pick={market:'Goals Over/Under',selection:'Over 1.5',odd:1.45,modelProbability:.8,dataScore:90,edgePP:11};
const candidate={fixtureId:1,match:'<script>unsafe</script> - Away',league:'League',kickoff:'2099-10-05T19:00:00Z',home:{name:'Home'},away:{name:'Away'},pick,profiles:{home:profile,away:profile},markets:[{...pick,eligible:true,reasons:[]}],risks:['Kalibrasyonsuz'],expectedGoals:{home:1.4,away:1},reasons:[]};
const leg={fixtureId:1,match:'Home - Away',league:'League',kickoff:candidate.kickoff,pick,result:{status:'pending'}};
const coupon={id:'c',originalOdd:2.1,independenceModelProduct:.64,legs:[leg,{...leg,fixtureId:2}],check:{status:'waiting',history:[]},result:{status:'pending'}};
let state={date:'2099-10-05',day:'2099-10-05',settings,api:{used:0,limit:2000,reserve:1500,remaining:6000},summary:{coupons:1,candidates:1,won:0,lost:0,pending:1,profitUnits:0},sessions:[{id:'s',createdAt:'2099-10-05',status:'complete',couponCount:1}],availableDates:['2099-10-05'],session:{id:'s',status:'complete',createdAt:'2099-10-05',coupons:[coupon],candidates:[candidate]},discovery:{leagues:[]},busy:false,storageError:null,job:null};
const requests=[],context={window:{},document:{getElementById:node,createElement:tag=>new E(tag),querySelectorAll:()=>[]},Date,Intl,navigator:{clipboard:{writeText:async()=>{}}},apiFetch:async(url,options)=>{requests.push({url,options});return state;},showToast:()=>{}};
vm.runInNewContext(fs.readFileSync('public/banko_choices.js','utf8'),context);vm.runInNewContext(fs.readFileSync('public/banko_coupon_panel.js','utf8'),context);
(async()=>{await context.window.fetchBankoCoupon();assert.match(node('banko-api').textContent,/2000/);assert.equal(node('banko-setting-dailyLimit').value,2000);assert.equal(node('banko-date').value,'2099-10-05');assert(node('banko-coupons').children[0].className.includes('banko-waiting'),'Pending is not green approval');assert.match(collect(node('banko-candidates')),/<script>unsafe/,'Provider text stays inert textContent');assert(!fs.readFileSync('public/banko_coupon_panel.js','utf8').includes('innerHTML'));
    const grid=node('banko-candidates').children[0].children.find(n=>n.className==='banko-profile-grid');for(const p of grid.children){const main=p.children.find(n=>n.className==='table-wrap'&&collect(n).includes('Son 10 maçtan istatistik'));assert(!/Sarı kart|Kırmızı kart|xG/.test(collect(main)));const optional=p.children.find(n=>n.tagName==='details'&&collect(n).includes('İsteğe bağlı veriler'));assert(optional);assert(!optional.open,'Optional cards/xG starts collapsed');assert.match(collect(optional),/Sarı kart.*1\.63.*9\/10/);assert.match(collect(optional),/xG.*—.*0\/10/,'Missing xG is not shown as zero');}
    node('banko-setting-maxCoupons').value='7';context.window.markBankoDirty();await context.window.saveBankoSettings();const saved=requests.find(r=>r.url==='/api/banko-coupon/settings');assert.equal(JSON.parse(saved.options.body).maxCoupons,7,'Panel passes requested counts above two to the backend');
    await context.window.runBankoAction('results');const post=requests.find(r=>r.url==='/api/banko-coupon/results');assert(post);assert.equal(JSON.parse(post.options.body).date,'2099-10-05');assert.equal(JSON.parse(post.options.body).sessionId,'s');
    coupon.check.status='rejected';await context.window.fetchBankoCoupon();const rejected=node('banko-coupons').children[0];assert(rejected.className.includes('banko-rejected'));const action=rejected.children.find(e=>e.className==='banko-actions');assert.equal(action.children[0].disabled,true,'Rejected coupon cannot be copied as valid');
    const completeState=state;state={...state,busy:true,job:{id:'pause-job',sessionId:'s',status:'waiting-live',processed:1,total:2,message:'Canlı işlemi bekliyor'},session:{...state.session,status:'running',coupons:[]}};
    await context.window.fetchBankoCoupon();assert.match(node('banko-status').textContent,/Canlı taramayı bekliyor.*1\/2/);assert(node('banko-scan').disabled);assert(!node('banko-coupons').children[0].className.includes('error'));assert.match(collect(node('banko-coupons')),/aynı tarama otomatik devam edecek/);
    state={...state,job:{...state.job,status:'running',message:'Devam ediyor'}};await context.window.pollBankoCoupon();assert.match(collect(node('banko-coupons')),/Tarama sürüyor/);
    state={...completeState,storageError:'Store blocked'};await context.window.fetchBankoCoupon();assert.equal(node('banko-scan').disabled,true);assert.equal(node('banko-results').disabled,true);
    const routes={};require('./banko_routes').registerBankoRoutes({get:(p,f)=>routes['GET '+p]=f,post:(p,f)=>routes['POST '+p]=f},{banko:{busy:false,status:()=>state,settings:()=>state,start:()=>{throw Error('Protected');}},apiReady:()=>false});
    const res={code:200,status(n){this.code=n;return this;},json(v){this.body=v;return this;}};routes['POST /api/banko-coupon/scan']({body:{date:'2099-10-05'}},res);assert.equal(res.code,503);assert.equal(Object.keys(routes).length,9);
    const server=fs.readFileSync('server.js','utf8'),html=fs.readFileSync('public/index.html','utf8');assert(server.indexOf('createPanelAuth')<server.indexOf('registerBankoRoutes(app'));assert(server.includes('delete requestConfig.dinoBeforeAttempt'));assert.match(server,/typeof beforeAttempt === 'function'\) beforeAttempt\(\)/);assert(!fs.readFileSync('banko_coupon.js','utf8').includes('setInterval'));
    assert(html.includes('id="section-banko-coupon"'));assert(html.includes('SONUÇLARI GETİR · MANUEL'));assert(html.includes('banko_coupon_panel.js'));assert.equal(fs.readFileSync('index.html','utf8'),html);
    const countInput=html.match(/<input[^>]*id="banko-setting-maxCoupons"[^>]*>/)[0];assert(!/\bmax=/.test(countInput));assert.match(countInput,/min="1"/);assert.match(countInput,/step="1"/);assert(html.includes('en az 8 geçmiş lig maçı ve 3 ilgili saha maçı'));assert(html.includes('banko_coupon_panel.js?v=20261007banko5'));assert(html.includes('banko_coupon.css?v=20261007banko5'));assert(html.indexOf('/banko_choices.js')<html.indexOf('/banko_coupon_panel.js'));assert(html.includes('aynı tarama kaldığı yerden otomatik devam eder'));
    await require('./banko_alternative_panel.test')();
    console.log('Banko panel/routes: private auth ordering, dispatch hook, date/version selection, manual results, budget settings, inert provider text, rejected-copy guard, pending colors and synchronized HTML passed.');
})().catch(e=>{console.error(e);process.exitCode=1;});
