'use strict';
const assert=require('assert/strict'),fs=require('fs'),path=require('path'),P=require('./banko_scan_progress'),C=require('./public/banko_choices');
const {BankoCoupon,dayKey}=require('./banko_coupon');
const date='2099-10-05';
function setup({count=4,pas=[],pages=1,predictions=false,usage=0,target=2,limit=2000,fail=false}={}){
    fs.mkdirSync(path.join(__dirname,'test-temp'),{recursive:true});const directory=fs.mkdtempSync(path.join(__dirname,'test-temp/banko-resume-'));
    const state={now:new Date(date+'T08:00:00Z'),remaining:6000,calls:[],live:false,b:null};
    const fixtures=Array.from({length:count},(_,i)=>({fixture:{id:201+i,date:date+'T18:00:00Z',status:{short:'NS'}},league:{id:99,season:2099,name:'Test',country:'Test'},teams:{home:{id:1,name:'Ev '+i},away:{id:2,name:'Dep '+i}}}));
    fixtures.push({...fixtures[0],fixture:{...fixtures[0].fixture,id:999,date:date+'T21:10:00Z'}});fixtures.push(fixtures[0]);
    const history=Array.from({length:24},(_,i)=>({fixture:{id:1000+i,date:new Date(Date.parse(date+'T00:00:00Z')-(i+2)*86400000).toISOString(),status:{short:'FT'}},teams:{home:{id:i%2?2:1},away:{id:i%2?1:2}},score:{fulltime:{home:2,away:1},halftime:{home:1,away:0}},statistics:[]}));
    const apiGet=async(url,config)=>{config.dinoBeforeAttempt();assert(!state.live);state.calls.push(url);if(fail&&new URL(url,'https://invalid.test').pathname==='/odds')throw Error('Sent ambiguous provider failure');
        const u=new URL(url,'https://invalid.test'),id=Number(u.searchParams.get('fixture'));let response=[];
        if(u.pathname==='/fixtures'&&u.searchParams.has('date'))response=fixtures;
        else if(u.pathname==='/fixtures'&&u.searchParams.has('league'))response=history;
        else if(u.pathname==='/fixtures'&&u.searchParams.has('ids'))response=u.searchParams.get('ids').split('-').map(Number).map(id=>history.find(f=>f.fixture.id===id));
        else if(u.pathname==='/odds'&&!pas.includes(id))response=[{fixture:{id},update:state.now.toISOString(),bookmakers:[{id:8,name:'Bet365',bets:[{id:5,name:'Goals Over/Under',values:[{value:'Over 1.5',odd:'1.45'}]}]}]}];
        else if(u.pathname==='/leagues')response=[{seasons:[{year:2099,coverage:{predictions,injuries:false}}]}];
        else if(u.pathname==='/predictions')response=[{predictions:{advice:'Context only',percent:{home:'50%',draw:'25%',away:'25%'}}}];
        return {data:{response,errors:[],paging:{total:u.pathname==='/odds'?pages:1}}};};
    function instance(){state.b=new BankoCoupon({directory,apiGet,now:()=>state.now,canRun:()=>!state.live,getQuotaRemaining:()=>state.remaining,waitForLiveTick:async()=>{assert.equal(state.b.data.latestJob.status,'waiting-live');state.live=false;}});return state.b;}
    const b=instance();b.settings({maxCandidates:target,dailyLimit:limit,strengthLabEnabled:false});b.usage[dayKey(state.now)]=usage;b.saveUsage();
    return {state,b,directory,instance};
}
async function run(b,kind='scan',id=null){b.start(kind,date,id);await b.task;return b.data.sessions.at(-1);}
const oddsCalls=(state,id,page)=>state.calls.filter(url=>{const u=new URL(url,'https://invalid.test');return u.pathname==='/odds'&&Number(u.searchParams.get('fixture'))===id&&(page===undefined||Number(u.searchParams.get('page'))===page);}).length;
(async()=>{
    {const {b,state}=setup({count:6,pas:[201,202,204],target:2});const s=await run(b);assert.equal(s.status,'complete',s.reason);assert.equal(s.candidates.length,5);assert.equal(s.scanSummary.accepted,2);assert.equal(s.scanSummary.target,2);assert.equal(s.scanSummary.stopReason,'target');assert.equal(oddsCalls(state,206),0,'Stop only after two main selections, not after two PAS');assert.equal(oddsCalls(state,999),0,'Never enter next TSİ day');assert.equal(oddsCalls(state,201),1,'Duplicate fixture removed');assert.equal(b.status(date).summary.pas,3);}
    {const {b,state}=setup({count:3,pas:[201],target:100});const s=await run(b);assert.equal(s.scanSummary.accepted,2);assert.equal(s.scanSummary.stopReason,'day-exhausted');assert.equal(s.candidates.length,3);assert.equal(state.calls.filter(u=>new URL(u,'https://invalid.test').searchParams.has('date')).length,1);assert.equal(oddsCalls(state,999),0);}
    {const {b}=setup({count:3,pas:[201,202,203],target:100});const s=await run(b);assert.equal(s.scanSummary.accepted,0);assert.equal(s.coupons.length,0);assert.equal(s.status,'complete');assert.equal(s.scanSummary.stopReason,'day-exhausted');}
    {const {b,state}=setup({count:130,pas:Array.from({length:25},(_,i)=>201+i),target:100});const s=await run(b);assert.equal(s.status,'complete',s.reason);assert.equal(s.scanSummary.accepted,100);assert.equal(s.candidates.length,125);assert.equal(oddsCalls(state,326),0);assert.equal(s.scanSummary.stopReason,'target');assert(s.candidates.every(r=>r.fixtureId!==999));}
    {const {b,state}=setup({usage:14,limit:20,target:1});const s=await run(b);assert.equal(s.status,'complete','Exactly full budget may finish without more requests');assert.equal(s.scanSummary.accepted,1);assert.equal(state.calls.length,6);assert.equal(b.usage[dayKey(state.now)],20);}
    {const {b,state,instance}=setup({usage:14,limit:20,target:2});let s=await run(b);assert.equal(s.status,'waiting-budget',s.reason);assert.equal(s.scanProgress.cursor,1);assert.equal(s.candidates.length,1);assert(s.candidates[0].pick);assert.equal(b.data.latestJob.status,'waiting-budget');assert.equal(state.calls.length,6);assert.equal(s.apiUsed,6);assert.equal(b.status(date,s.id).scan.canResume,true);assert(!('fixtures' in b.status(date,s.id).session.scanProgress),'Internal fixture/odds checkpoint is not sent to panel');
        const id=s.id,frozen=JSON.stringify(s.candidates[0]),settings=JSON.stringify(s.settings),used=b.usage[dayKey(state.now)];const reload=instance();reload.load();assert.equal(reload.storageError,null);assert.equal(state.calls.length,6,'Load and status do not auto-dispatch');assert.equal(reload.usage[dayKey(state.now)],used);
        await run(reload,'resume',id);assert.equal(state.calls.length,6,'Resume with exhausted budget sends no request');reload.settings({dailyLimit:40,maxCandidates:100,minModelProbability:90});s=await run(reload,'resume',id);assert.equal(s.status,'complete',s.reason);assert.equal(reload.data.sessions.length,1);assert.equal(s.id,id);assert.equal(s.scanSummary.target,2,'Original model/target snapshot preserved');assert.equal(JSON.stringify(s.settings),settings);assert.equal(JSON.stringify(s.candidates[0]),frozen);assert.equal(oddsCalls(state,201),1,'Completed analysis never fetched again');assert.equal(s.apiUsed,state.calls.length);assert.equal(s.scanSummary.accepted,2);assert.throws(()=>reload.start('resume',date,id));assert.throws(()=>reload.start('resume','2099-10-06',id));}
    {const {b,state,instance}=setup({count:1,pages:2,usage:18,limit:20,target:1});let s=await run(b);assert.equal(s.status,'waiting-budget');assert.equal(s.scanProgress.pending.oddsPages.page,2);assert.equal(oddsCalls(state,201,1),1);const reload=instance();reload.load();reload.settings({dailyLimit:40});s=await run(reload,'resume',s.id);assert.equal(s.status,'complete',s.reason);assert.equal(oddsCalls(state,201,1),1,'Successful first odds page survives restart');assert.equal(oddsCalls(state,201,2),1);}
    {const {b,state,instance}=setup({count:1,pages:2,usage:18,limit:20,target:1});let s=await run(b);s.status='running';b.data.latestJob.status='waiting-live';s.apiUsed=0;b.save();const reload=instance();reload.load();assert.equal(reload.storageError,null);assert.equal(reload.data.sessions[0].status,'interrupted');assert(reload.status(date,s.id).scan.canResume);assert.equal(reload.status(date,s.id).session.apiUsed,2,'Per-session ledger survives interruption before finalization');reload.settings({dailyLimit:40});s=await run(reload,'resume',s.id);assert.equal(s.status,'complete');assert.equal(s.apiUsed,state.calls.length);assert.equal(oddsCalls(state,201,1),1);}
    {const {b,state,instance}=setup({count:1,predictions:true,usage:14,limit:20,target:1});let s=await run(b);assert.equal(s.status,'waiting-budget');assert(s.scanProgress.pending.row?.pick,'Computed pending row persisted before context request');const count=state.calls.length,reload=instance();reload.load();reload.settings({dailyLimit:40});s=await run(reload,'resume',s.id);assert.equal(s.status,'complete');assert.equal(state.calls.length,count+1,'Only the missing context request continues');assert(s.candidates[0].apiPrediction.contextOnly);}
    {const {b,state}=setup({usage:14,limit:20,target:3});let s=await run(b);const count=state.calls.length,id=s.id;state.now=new Date('2099-10-06T08:00:00Z');s=await run(b,'resume',id);assert.equal(s.status,'complete');assert.equal(s.date,date);assert.equal(state.calls.length,count,'Next-day resume skips begun original fixtures without new API');assert.equal(s.scanSummary.accepted,0);assert.equal(s.scanSummary.stopReason,'day-exhausted');assert(s.candidates.every(r=>!r.pick));}
    {const {b,state}=setup({target:3});const old=b.buildCandidate;b.buildCandidate=async(...args)=>{const row=await old.apply(b,args);if(row.fixtureId===201)state.remaining=1500;return row;};let s=await run(b);assert.equal(s.status,'waiting-budget');assert.match(s.reason,/rezerv/);const count=state.calls.length;state.remaining=6000;s=await run(b,'resume',s.id);assert.equal(s.status,'complete');assert(state.calls.length>count);assert.equal(oddsCalls(state,201),1);}
    {const {b,state,instance}=setup({fail:true});const s=await run(b);assert.equal(s.status,'partial');assert.equal(b.status(date,s.id).scan.canResume,false);const reload=instance();reload.load();assert.equal(reload.storageError,null);assert.throws(()=>reload.start('resume',date,s.id));assert.equal(oddsCalls(state,201),1,'Sent provider failures never retried');}
    {const rows=[{fixtureId:1,match:'Later',league:'L',kickoff:'2099-10-05T17:00Z',pick:{}},{fixtureId:2,match:'Early PAS',league:'L',kickoff:'2099-10-05T01:00Z',pick:null,strengthLab:{pick:{}}},{fixtureId:3,match:'Early',league:'L',kickoff:'2099-10-05T14:00Z',pick:{}},{fixtureId:4,match:'Later PAS',league:'L',kickoff:'2099-10-05T18:00Z',pick:null}];const before=JSON.stringify(rows);assert.deepEqual(C.displayRows(rows).map(r=>r.fixtureId),[3,1]);assert.deepEqual(C.displayRows(rows,true).map(r=>r.fixtureId),[3,1,2,4]);assert.deepEqual(C.displayRows(rows,true,'PAS').map(r=>r.fixtureId),[2,4]);assert.equal(P.selected(rows[1]),false,'LAB-only picks do not fill the main target');assert.equal(JSON.stringify(rows),before);}
    console.log('Banko eligible cap/resume: PAS excluded, exact TSİ day/no spill, target shortfall/no forced picks, durable budget and reserve checkpoints, restart/manual resume, frozen settings/rows, paged odds, context-only continuation, no repeats/ambiguous retries, old-day safety and ordered inert views passed.');
})().catch(e=>{console.error(e);process.exitCode=1;});
