'use strict';
const assert=require('assert/strict'),ML=require('./banko_market_lab'),M=require('./banko_model'),{DEFAULTS,BankoCoupon}=require('./banko_coupon');
const now=new Date('2099-10-05T08:00:00Z'),settings={...DEFAULTS},profile={last20:{games:20},venueSummary:{games:10},stats:{'Corner Kicks':{games:9,mean:6},'Total Shots':{games:9,mean:16},'Shots on Goal':{games:9,mean:6}}};
const quote=(id,value,name='Test',p=.8,odd=1.5)=>({key:id+'|'+value,betId:id,market:name,selection:value,odd,spec:M.specFor(id,value),modelProbability:p,dataScore:100});
const base={fixtureId:99,home:{id:1},away:{id:2},capturedAt:now.toISOString(),oddsUpdatedAt:now.toISOString(),kickoff:'2099-10-05T19:00:00Z',expectedGoals:{home:2.2,away:1.1},profiles:{home:structuredClone(profile),away:structuredClone(profile)},markets:[]};
const run=(markets,extra={})=>ML.analyse({...structuredClone(base),markets,...extra},settings,now);
const accepted=run([quote(12,'Home/Draw'),quote(5,'Over 2.5','Test',.775),quote(16,'Under 1.5','Test',.99),quote(6,'Under 1.5','Test',.99),quote(20,'Draw/Away','Test',.99),quote(8,'Yes','Test',.76)]);
assert.equal(accepted.pick.betId,12);assert.equal(accepted.nearbyOver.betId,5);assert.equal(accepted.qualified,3);
assert.equal(run([quote(12,'Home/Draw'),quote(5,'Over 2.5','Test',.769)]).nearbyOver,null);
assert.equal(run([quote(5,'Under 2.5'),quote(27,'Yes'),quote(10,'2-1'),quote(7,'Home/Home'),quote(11,'1st Half')]).pick,null);
for(const id of [5,6,26,16,17,8,34,35,27,28,1,12]){const value=[8,34,35].includes(id)?'No':[27,28].includes(id)?'No':id===1?'Home':id===12?'Home/Draw':'Over 1.5';assert(run([quote(id,value)]).pick,'retained '+id);}
for(const id of [3,13,20])assert.equal(run([quote(id,id===20?'Draw/Away':'Away')]).pick,null);
const combo=quote(25,'Home/Over 2.5','Result/Total Goals');const s=ML.extraSpec(combo);assert(s);const p=ML.probability(s,base),expected=M.pairs(2.2,1.1).filter(r=>r.home>r.away&&r.home+r.away>2.5).reduce((sum,r)=>sum+r.p,0);assert.equal(p,expected);
assert.notEqual(p,M.probability({kind:'winner',code:'1',period:'full'},base.expectedGoals)*M.probability({kind:'total',direction:'over',line:2.5,period:'full'},base.expectedGoals));
for(const m of [quote(25,'Away/Over 2.5','Result/Total Goals'),quote(25,'Home/Over 2','Result/Total Goals'),quote(25,'Home/Over 2.5','Unverified')])assert.equal(ML.extraSpec(m),null);
const comboRow={...base,expectedGoals:{home:3.5,away:.4},markets:[quote(25,'Home/Over 2.5','Result/Total Goals')]};assert.equal(ML.analyse(comboRow,settings,now).pick.spec.kind,'homeOver');
const stats=run([quote(45,'Over 8.5','Corners Over Under'),quote(57,'Over 3.5','Home Corners Over/Under'),quote(211,'Over 23.5','Total Shots'),quote(87,'Over 7.5','Total ShotOnGoal'),quote(276,'Over 15.5','Away Player Shots Total')]);
assert.equal(stats.pick,null,'Count diagnostic never becomes core pick');assert.equal(stats.experimental.length,3);assert.equal(stats.unsupportedShotQuotes,1);
assert(stats.experimental.every(m=>m.experimental&&m.statInput));assert(!ML.extraSpec(quote(45,'Over 9','Corners Over Under')));assert(!ML.extraSpec(quote(211,'Under 27.5','Total Shots')));
const weak=structuredClone(base.profiles);weak.away.stats['Total Shots'].games=7;assert.equal(run([quote(211,'Over 23.5','Total Shots')],{profiles:weak}).experimental.length,0);
for(const [changes,conf] of [[{oddsUpdatedAt:'2099-10-04T08:00:00Z'},settings],[{kickoff:now.toISOString()},settings],[{}, {...settings,minModelProbability:90}]])assert.equal(ML.analyse({...base,markets:[quote(5,'Over 1.5')],...changes},conf,now).pick,null);
const fixture={fixture:{status:{short:'FT'}},teams:{home:{id:1},away:{id:2}},score:{fulltime:{home:3,away:1},halftime:{home:1,away:0}},statistics:[1,2].map(id=>({team:{id},statistics:[{type:'Corner Kicks',value:id===1?6:4},{type:'Total Shots',value:16},{type:'Shots on Goal',value:6}]}))};
assert.equal(ML.settle({...combo,spec:s},fixture).status,'won');assert.equal(ML.settle({...combo,spec:s},{...fixture,score:{fulltime:{home:2,away:2}}}).status,'lost');
for(const m of stats.experimental)assert.equal(ML.settle(m,fixture).status,'won');
const corner=stats.experimental.find(m=>m.spec.family==='corners');assert.equal(ML.settle(corner,{...fixture,statistics:[]}).status,'pending');assert.equal(ML.settle(corner,{...fixture,fixture:{status:{short:'AET'}}}).status,'pending');
assert.equal(ML.settle(corner,{...fixture,statistics:fixture.statistics.map(t=>({...t,team:{id:999}}))}).status,'pending');
const zero={...fixture,statistics:fixture.statistics.map(t=>({...t,statistics:[{type:'Corner Kicks',value:0}]}))};assert.equal(ML.settle(corner,zero).status,'lost','Real zero is not missing');
const half=run([quote(6,'Over 0.5')]).pick;assert.equal(ML.settle(half,{...fixture,score:{fulltime:{home:3,away:1}}}).status,'pending');assert.equal(ML.settle(half,fixture).status,'won');
const row={...structuredClone(base),markets:[quote(5,'Over 1.5')],reasons:[],risks:[]};const off=new BankoCoupon({now:()=>now}),on=new BankoCoupon({now:()=>now});const a=structuredClone(row),b=structuredClone(row);off.evaluateCandidate(a,{...settings,marketLabEnabled:false});on.evaluateCandidate(b,settings);const {marketLab,...primary}=b;assert.deepEqual(primary,a);assert(marketLab);const before=JSON.stringify(b);ML.analyse(b,settings,now);assert.equal(JSON.stringify(b),before,'Pure LAB does not mutate its input');
assert.equal(ML.selections({marketLab:accepted}).length,2);assert.equal(ML.summary({candidates:[{marketLab:accepted}]}).core.pending,2);
console.log('Market LAB: exact market semantics, unchanged goal model, no ALT/half DC, independent gates, nearby OVER, joint combo, isolated count diagnostics, 8+ samples, strict normal-time/stat settlement, missing != zero and immutable primary passed.');
