'use strict';
const assert=require('assert/strict'),M=require('./banko_model');
const profile=()=>({last20:{games:20},venueSummary:{games:10},stats:{'Corner Kicks':{games:10,mean:5}}});
const p={home:1.4,away:1.0,phase:{homeFirst:.6,awayFirst:.45,homeSecond:.8,awaySecond:.55}};
const prob=(id,v)=>M.probability(M.specFor(id,v),p,profile(),profile());
assert.equal(M.finite(null),null);assert.equal(M.finite(''),null);assert.equal(M.finite(false),null);
assert.equal(M.specFor(4,'Home -0.25'),null);assert.equal(M.specFor(5,'Over 2'),null);assert.equal(M.specFor(5,'Over 2.25'),null);assert.equal(M.specFor(80,'Over 3.5'),null);assert.equal(M.specFor(276,'Over 10.5'),null);
assert(Math.abs(prob(1,'Home')+prob(1,'Draw')+prob(1,'Away')-1)<1e-10);
assert(Math.abs(prob(12,'Home/Draw')-prob(1,'Home')-prob(1,'Draw'))<1e-10);
assert(Math.abs(prob(8,'Yes')-(1-Math.exp(-1.4))*(1-Math.exp(-1)))<1e-10);
assert(Math.abs(prob(5,'Over 1.5')+prob(5,'Under 1.5')-1)<1e-10);
assert.equal(M.probability(M.specFor(6,'Over 0.5'),{home:1,away:1,phase:null},profile(),profile()),null);
let htft=0;for(const a of ['Home','Draw','Away'])for(const b of ['Home','Draw','Away'])htft+=prob(7,a+'/'+b);assert(Math.abs(htft-1)<1e-8);
const fixture={fixture:{id:1,date:'2099-01-01T12:00:00Z',status:{short:'FT'}},teams:{home:{id:11},away:{id:12}},score:{fulltime:{home:2,away:1},halftime:{home:1,away:0}},goals:{home:2,away:1}};
const settle=(id,value,f=fixture)=>M.settle({odd:1.5,spec:M.specFor(id,value)},f);
assert.equal(settle(1,'Home').status,'won');assert.equal(settle(1,'Away').status,'lost');assert.equal(settle(12,'Draw/Away').status,'lost');assert.equal(settle(8,'Yes').status,'won');
assert.equal(settle(5,'Over 2.5').status,'won');assert.equal(settle(5,'Under 2.5').status,'lost');assert.equal(settle(6,'Over 0.5').status,'won');assert.equal(settle(26,'Over 1.5').status,'won');
assert.equal(settle(16,'Over 1.5').status,'won');assert.equal(settle(17,'Over 1.5').status,'lost');assert.equal(settle(27,'No').status,'won');assert.equal(settle(28,'Yes').status,'lost');
assert.equal(settle(7,'Home/Home').status,'won');assert.equal(settle(11,'2nd Half').status,'won');assert.equal(settle(31,'1:0').status,'won');
assert.equal(settle(5,'Over 0.5',{...fixture,score:{fulltime:{home:null,away:null}}}).status,'pending');
assert.equal(settle(7,'Home/Home',{...fixture,score:{fulltime:fixture.score.fulltime,halftime:{home:3,away:0}}}).status,'pending');
assert.equal(settle(5,'Over 3.5',{...fixture,fixture:{status:{short:'AET'}},goals:{home:4,away:1}}).status,'lost','Normal time only, no AET goals');
assert.equal(settle(5,'Over 0.5',{...fixture,fixture:{status:{short:'AWD'}}}).status,'pending');
assert.equal(settle(45,'Over 6.5',{...fixture,statistics:[{statistics:[{type:'Corner Kicks',value:null}]},{statistics:[{type:'Corner Kicks',value:6}]}]}).status,'pending');
assert.equal(M.pastFixture(fixture,Date.parse('2099-01-01T14:00:00Z')),null,'Completion margin excludes not-yet-completed history');
const wrongHt=M.pastFixture({...fixture,score:{...fixture.score,halftime:{home:3,away:0}}},Date.parse('2099-01-02T00:00:00Z'));assert.equal(wrongHt.ht,null);
const rows=[{fixture:{id:1},update:'2099-01-01T10:00:00Z',bookmakers:[{id:8,name:'Bet365',bets:[{id:5,name:'Goals Over/Under',values:[{value:'Over 1.5',odd:'1.5'}]}]}]},
    {fixture:{id:1},update:'2099-01-01T11:00:00Z',bookmakers:[{id:8,name:'Bet365',bets:[{id:80,name:'Cards',values:[{value:'Over 3.5',odd:'1.5'}]}]}]}];
const odds=M.parseMarkets(rows,1);assert.equal(odds.markets.length,1);assert.equal(odds.markets[0].betId,80,'New missing markets are not filled with old prices');
const settings={minLegOdd:1.4,maxLegOdd:2.2,maxOddsAgeHours:6,minModelProbability:65,minEdgePP:0,marketFamilies:['goals','corners']};
const rejected=M.evaluateMarkets(odds,p,{home:profile(),away:profile()},settings,new Date('2099-01-01T12:00:00Z'),'2099-01-01T18:00:00Z');assert.equal(rejected[0].eligible,false);
const cornerOdds={update:'2099-01-01T11:00:00Z',markets:[{key:'45|Over 6.5',betId:45,odd:1.5,spec:M.specFor(45,'Over 6.5')}]};assert.equal(M.evaluateMarkets(cornerOdds,p,{home:profile(),away:profile()},settings,new Date('2099-01-01T12:00:00Z'),'2099-01-01T18:00:00Z')[0].eligible,false,'Diagnostic corner model is never silently a coupon pick');
assert.deepEqual(M.DATA_POLICY,{minimumHistoryMatches:8,minimumVenueMatches:3,minimumPhaseMatches:10});
const goalOdds={update:'2099-01-01T11:00:00Z',markets:[{key:'5|Under 3.5',betId:5,odd:1.4,spec:M.specFor(5,'Under 3.5')}]};
const limited=(games=8,venue=3)=>({...profile(),last20:{games},venueSummary:{games:venue}});
const evaluate=(home,away=limited())=>M.evaluateMarkets(goalOdds,p,{home,away},settings,new Date('2099-01-01T12:00:00Z'),'2099-01-01T18:00:00Z')[0];
assert.equal(evaluate(limited()).eligible,true,'Exactly 8 general + 3 venue matches passes the data gate');
assert.equal(evaluate(limited(9,4)).eligible,true,'9 matches is sufficient; no exact-10 requirement');
for(const [games,venue] of [[7,3],[8,2]])for(const side of ['home','away']){const pair={home:limited(),away:limited()};pair[side]=limited(games,venue);const result=evaluate(pair.home,pair.away);assert.equal(result.eligible,false,side+' must independently satisfy both minimums');assert(result.reasons.some(r=>r.includes('8 geçmiş lig maçı ve 3 saha maçı')));}
assert.equal(evaluate(limited()).dataScore,36,'Lower coverage does not inflate the existing data score');
const history=Array.from({length:10},(_,i)=>({id:500+i,date:new Date(Date.parse('2098-12-30T12:00:00Z')-i*86400000).toISOString(),homeId:11,awayId:12,home:2,away:1,ht:{home:1,away:0}}));
const hp=M.teamProfile(history,11,'home',{}),ap=M.teamProfile(history,12,'away',{});
for(const field of ['Yellow Cards','Red Cards','expected_goals']){assert.equal(hp.stats[field].games,0);assert.equal(hp.stats[field].mean,null);}
assert.equal(evaluate(hp,ap).eligible,true,'Missing cards and xG remain optional and never become zero');
const base={home:1.4,away:1};assert(M.expectedGoals(hp,ap,base).phase,'10 valid halves enable phase markets');
for(const side of ['home','away']){const pair={home:hp,away:ap};pair[side]={...pair[side],phases:{...pair[side].phases,games:9}};assert.equal(M.expectedGoals(pair.home,pair.away,base).phase,null,'9 phase records must not enable half/HTFT markets');}
const missingPhase=M.expectedGoals({...hp,phases:{...hp.phases,games:9}},ap,base);assert.equal(M.probability(M.specFor(7,'Home/Home'),missingPhase,hp,ap),null);
const optimizerSettings={minCouponOdd:1.95,maxCouponOdd:2.4,minSingleOdd:1.8,maxSingleOdd:2.2,maxCoupons:2};
const candidate=(id,odd=.0)=>({fixtureId:id,pick:{odd:odd||1.45,modelProbability:.8,dataScore:90},capturedAt:'2099-01-01'});
const coupons=M.optimize([candidate(1),candidate(2),candidate(3),candidate(4)],optimizerSettings,'s');assert.equal(coupons.length,2);assert.equal(new Set(coupons.flatMap(c=>c.legs.map(l=>l.fixtureId))).size,4);
assert.equal(M.optimize([candidate(1)],optimizerSettings,'s').length,0,'Do not force low-price single or add a third leg');
assert.equal(M.optimize([candidate(1,1.9)],optimizerSettings,'s')[0].legs.length,1);
const many=Array.from({length:10},(_,i)=>candidate(i+1));
const three=M.optimize(many,{...optimizerSettings,maxCoupons:3},'many');assert.equal(three.length,3,'More than two coupons can be requested');
const available=M.optimize(many,{...optimizerSettings,maxCoupons:1000},'many');assert.equal(available.length,5,'High requested count never forces extra candidates');
assert(available.every(c=>c.legs.length<=2));assert.equal(new Set(available.flatMap(c=>c.legs.map(l=>l.fixtureId))).size,10,'No fixture reused between coupons');
console.log('Banko model: market identities, probabilities, half-time consistency, missing data, strict normal-time settlement, as-of history, quote freshness and coupon diversification passed.');
