'use strict';
const fs=require('fs'),assert=require('assert/strict'),vm=require('vm'),ML=require('./banko_market_lab'),{DEFAULTS}=require('./banko_coupon');
class E{constructor(tag='div'){this.tagName=tag;this.children=[];this.textContent='';this.className='';this.dataset={};this.value='';this.checked=false;this.disabled=false;this.hidden=false;this.attributes={};}setAttribute(k,v){this.attributes[k]=String(v);}appendChild(n){this.children.push(n);return n;}append(...nodes){nodes.forEach(n=>this.appendChild(n));}replaceChildren(...nodes){this.children=[];this.append(...nodes);}}
const nodes=new Map(),node=id=>{if(!nodes.has(id))nodes.set(id,new E());return nodes.get(id);},text=e=>[e.textContent,...e.children.map(text)].join(' '),tags=e=>[e.tagName,...e.children.flatMap(tags)];
const pick={key:'12|Home/Draw',betId:12,selection:'Home/Draw',spec:{kind:'doubleChance',period:'full',code:'1X',family:'result'},odd:1.5,modelProbability:.8,dataScore:100,edgePP:13.33,eligible:true,reasons:[]},over={...pick,key:'5|Over 2.5',betId:5,selection:'Over 2.5',modelProbability:.775,spec:{kind:'total',period:'full',direction:'over',line:2.5,family:'goals'}};
const row={fixtureId:1,match:'Home - Away',league:'Test',kickoff:'2099-10-05T18:00:00Z',home:{name:'Home'},away:{name:'Away'},pick,markets:[],profiles:null,risks:[],reasons:[],marketLab:{version:ML.VERSION,pick,nearbyOver:over,experimental:[],results:{[pick.key]:{status:'won',score:'2-2'}},rejected:[{selection:'<script>unsafe</script>',odd:1.5,reasons:['No samples']}],inspected:3,qualified:2,disclaimer:'Salt okunur LAB',unsupportedShotQuotes:1}};
let state={date:'2099-10-05',day:'2099-10-05',settings:{...DEFAULTS},api:{used:0,limit:2000,reserve:1500,remaining:6000},scan:{target:100,accepted:1,examined:1,total:1,window:'18:00–23:59 TSİ'},summary:{coupons:0,candidates:1,selected:1,pas:0,won:0,lost:0,pending:0,profitUnits:0},sessions:[],availableDates:[],session:{id:'s',status:'complete',settings:DEFAULTS,coupons:[],candidates:[row]},busy:false};
const requests=[],context={window:{},document:{getElementById:node,createElement:t=>new E(t),querySelectorAll:()=>[]},Date,Intl,apiFetch:async(url,options)=>{requests.push({url,options});if(url.endsWith('/settings'))state={...state,settings:JSON.parse(options.body)};return state;},showToast(){}};
for(const file of ['public/banko_choices.js','public/banko_market_panel.js','public/banko_coupon_panel.js'])vm.runInNewContext(fs.readFileSync(file,'utf8'),context);
(async()=>{const before=JSON.stringify(row),card=context.window.BankoMarketPanel.card(row,'s');assert.match(text(card),/Market LAB.*1X/);assert.match(text(card),/YAKIN ÜST/);assert.match(text(card),/Kazandı.*2-2/);assert.match(text(card),/<script>unsafe/);assert.match(text(card),/Oyuncu\/takım şutu adı belirsiz/);assert(!tags(card).some(t=>['input','button','textarea'].includes(t)),'Read-only card has no save/refresh/send controls');assert.equal(requests.length,0);assert.equal(JSON.stringify(row),before);assert.match(text(context.window.BankoMarketPanel.card({...row,marketLab:null})),/sonradan değiştirilmez/);
    await context.window.fetchBankoCoupon();assert.equal(node('banko-setting-scanWindowMode').value,'all-day');assert(node('banko-setting-scanFrom').disabled);assert(node('banko-setting-marketLabEnabled').checked);assert.match(node('banko-progress').textContent,/18:00–23:59/);assert.match(text(node('banko-candidates')),/Market LAB/);
    node('banko-setting-scanWindowMode').value='range';context.window.bankoWindowChanged();assert(!node('banko-setting-scanFrom').disabled);node('banko-setting-scanFrom').value='18:00';node('banko-setting-scanTo').value='23:30';await context.window.fetchBankoCoupon();assert.equal(node('banko-setting-scanFrom').value,'18:00','Polling does not overwrite dirty settings');await context.window.saveBankoSettings();const posted=JSON.parse(requests.find(r=>r.url.endsWith('/settings')).options.body);assert.equal(posted.scanWindowMode,'range');assert.equal(posted.scanFrom,'18:00');assert.equal(posted.scanTo,'23:30');assert.equal(posted.marketLabEnabled,true);node('banko-setting-scanWindowMode').value='all-day';context.window.bankoWindowChanged();assert(node('banko-setting-scanTo').disabled);assert.equal(JSON.stringify(row),before);
    const html=fs.readFileSync('public/index.html','utf8');assert.equal(html,fs.readFileSync('index.html','utf8'));assert(html.indexOf('/banko_market_panel.js')<html.indexOf('/banko_coupon_panel.js'));assert(html.includes('banko_market.css?v=20261010market1'));assert.match(html,/value="all-day">Tüm gün/);assert.match(html,/type="time" id="banko-setting-scanFrom"/);const source=fs.readFileSync('public/banko_market_panel.js','utf8');assert(!/apiFetch|fetch\(|innerHTML|sendMessage|setInterval/.test(source));assert.match(fs.readFileSync('public/banko_market.css','utf8'),/var\(--ui-/);
    console.log('Market panel: inert safe-text card, separate nearby OVER/stat diagnostics, legacy archive hints, independent outcome, no provider/send/save controls, all-day/range fields, dirty settings preserved, saved HH:mm strings and dual HTML/theme contract passed.');
})().catch(e=>{console.error(e);process.exitCode=1;});
