'use strict';
const assert=require('assert/strict'),fs=require('fs'),vm=require('vm');
class E{constructor(tag='div'){this.tagName=tag;this.children=[];this.textContent='';this.className='';this.dataset={};this.value='';this.checked=false;this.disabled=false;this.open=false;}appendChild(n){this.children.push(n);return n;}append(...nodes){nodes.forEach(n=>this.appendChild(n));}replaceChildren(...nodes){this.children=[];this.append(...nodes);}}
const nodes=new Map(),node=id=>{if(!nodes.has(id))nodes.set(id,new E());return nodes.get(id);},all=e=>[e,...e.children.flatMap(all)],text=e=>all(e).map(n=>n.textContent).join(' ');
const context={window:{},document:{getElementById:node,createElement:t=>new E(t)}};vm.runInNewContext(fs.readFileSync('public/banko_choices.js','utf8'),context);vm.runInNewContext(fs.readFileSync('public/banko_strength_panel.js','utf8'),context);const P=context.window.BankoStrengthPanel;
const pick={key:'5|Over 1.5',selection:'Over 1.5',spec:{kind:'total',period:'full',direction:'over',line:1.5},odd:1.5,modelProbability:.8},other={...pick,key:'20|Home/Draw',selection:'Home/Draw',spec:{kind:'doubleChance',period:'first',code:'1X'},odd:1.6};
const base={match:'Home - Away',league:'Test League',home:{name:'Home'},away:{name:'Away'},pick,expectedGoals:{home:1.4,away:1},marketResults:{[pick.key]:{status:'won',score:'2-1'}},reasons:[],strengthLab:{version:'lab',pick:other,expectedGoals:{home:1.5,away:.9},historyMatches:100,inputCutoffDay:'2099-10-04',capturedAt:'2099-10-05',results:{main:{status:'lost'}},reasons:[],strengths:{home:{games:20,effectiveMatches:18,attackIndex:120,concedingIndex:90,powerIndex:133},away:{games:20,effectiveMatches:18,attackIndex:90,concedingIndex:110,powerIndex:82}}}};
const rows=Array.from({length:12},(_,i)=>({...structuredClone(base),fixtureId:i+1,id:'r'+i,match:'Match '+(i+1)}));rows[1].strengthLab.pick=pick;rows[2].strengthLab.pick=null;rows[3].strengthLab=undefined;rows[4].match='<img src=x onerror=unsafe> - Away';
const stat={total:3,pas:2,won:1,lost:1,pending:1,hitRate:50,netUnits:-.5,roi:-25},data={session:{id:'s',candidates:rows},strengthComparison:{available:true,fixtures:11,same:1,different:10,main:stat,lab:stat,disclaimer:'Only this session'},busy:false};
const before=JSON.stringify(data);P.render(data);assert.equal(node('banko-strength-list').children.length,10);assert.match(text(node('banko-strength-summary')),/Mevcut.*Güç LAB/);assert.match(text(node('banko-strength-list')),/Kazandı.*Kaybetti/);assert.match(text(node('banko-strength-list')),/İLK YARI · Çifte şans · 1X/);
node('banko-strength-next').onclick();assert.equal(node('banko-strength-list').children.length,2);node('banko-strength-prev').onclick();const card=all(node('banko-strength-list')).find(n=>n.className==='banko-strength-card');card.open=true;card.ontoggle();P.render(data);assert(all(node('banko-strength-list')).find(n=>n.className==='banko-strength-card').open);
node('banko-strength-different').checked=true;node('banko-strength-different').onchange();assert.equal(node('banko-strength-list').children.length,10,'Exclude same/no-LAB; include main vs PAS');node('banko-strength-search').value='Match 3';node('banko-strength-search').oninput();assert.equal(node('banko-strength-list').children.length,1);assert.match(text(node('banko-strength-list')),/PAS/);
assert.match(text(P.card(rows[3])),/Bu eski sürüme sonradan LAB tahmini eklenmez/);assert.equal(JSON.stringify(data),before,'Read-only UI never mutates original session/results');
const source=fs.readFileSync('public/banko_strength_panel.js','utf8');assert(!/apiFetch|\bfetch\(|XMLHttpRequest|WebSocket|setInterval|innerHTML/.test(source),'No background calls, writes or HTML interpolation');assert(!all(P.card(base)).some(n=>n.tagName==='button'),'Shadow has no main/manual/Telegram mutation button');
const html=fs.readFileSync('public/index.html','utf8');assert(html.includes('data-panel-banko-tab="comparison"'));assert(html.includes('banko-setting-strengthLabEnabled'));assert(html.indexOf('/banko_strength_panel.js')<html.indexOf('/banko_coupon_panel.js'));assert.equal(html,fs.readFileSync('index.html','utf8'));
console.log('Banko strength panel: existing/new model labels, market/odds/goals/reasons/results, search/difference/PAS/pagination, immutable legacy and snapshots, inert text and no API/mutation passed.');
