const assert=require('assert');
const fs=require('fs');
const vm=require('vm');

const server=fs.readFileSync('server.js','utf8');
const moduleSource=fs.readFileSync('coupon_lab.js','utf8');
const html=fs.readFileSync('public/index.html','utf8');
const rootHtml=fs.readFileSync('index.html','utf8');
const panel=fs.readFileSync('public/coupon_lab_panel.js','utf8');

assert.ok(server.includes("app.get('/api/coupon-lab'"));
assert.ok(server.includes("process.env.MAC_YAKALA_V21_TELEGRAM_ENABLED || 'false'"));
assert.ok(server.includes("Telegram: V24 Ana aktif"));
assert.ok(server.includes("app.post('/api/coupon-lab/scan'"));
assert.ok(server.includes("app.post('/api/coupon-lab/settings'"));
assert.ok(server.includes("app.post('/api/coupon-lab/settle'"));
assert.ok(moduleSource.includes("/fixtures?date=${targetDay}&timezone=Europe%2FIstanbul"));
assert.ok(moduleSource.includes('if (this.includeTomorrow) scanDays.push'));
assert.ok(server.includes("telegram: false"));
assert.ok(server.includes('setInterval(couponLabClock, 60000)'));
assert.ok(html.includes('id="section-coupon-lab"'));
assert.ok(html.includes('BUGÜNÜ ŞİMDİ TARA'));
assert.ok(html.includes('id="coupon-setting-enabled"'));
assert.ok(html.includes('id="coupon-setting-scan-time"'));
assert.ok(html.includes('id="coupon-setting-tomorrow"'));
assert.ok(html.includes('id="coupon-setting-final-minutes"'));
assert.ok(html.includes('id="coupon-setting-budget"'));
assert.ok(html.includes('id="coupon-setting-max-candidates"'));
assert.ok(html.includes('id="coupon-setting-max-selected"'));
assert.ok(!html.includes('id="coupon-setting-max-double-chance"'));
assert.ok(!panel.includes('maxDoubleChance'));
assert.ok(html.includes('İY/MS Kupon LAB'));
assert.ok(panel.includes('Alternatif analiz (kupona dahil değil)'));
assert.ok(moduleSource.includes("mode:'htft-only'"));
assert.ok(html.includes('AYARLARI KAYDET'));
assert.ok(html.includes('/coupon_lab_panel.js?v=20261005htft'));
assert.ok(html.includes('SONUÇLARI GÜNCELLE'));
assert.strictEqual(html,rootHtml);
assert.doesNotThrow(()=>new vm.Script(panel));
assert.ok(!panel.includes('innerHTML'));
assert.ok(panel.includes("apiFetch('/api/coupon-lab/scan'"));
assert.ok(panel.includes("apiFetch('/api/coupon-lab/settings'"));
assert.ok(panel.includes("apiFetch('/api/coupon-lab/settle'"));
assert.ok(panel.includes('BUGÜN + YARINI ŞİMDİ TARA'));
assert.ok(panel.includes('piyasa %'));
console.log('Coupon LAB server/panel contract: persistent controls, manual day scope, safe renderer and no Telegram passed.');
