'use strict';
const assert=require('assert/strict'),fs=require('fs'),os=require('os'),path=require('path'),vm=require('vm');
const {SharingSettings}=require('./sharing_settings');
const {SharingDelivery}=require('./sharing_delivery');
const {createPanelAuth}=require('./panel_auth');
const {formatSignal,TelegramDelivery,WIN_TEXT}=require('./mac_yakala_telegram');
const {oauthHeader,createXPublisher,formatXSignal}=require('./x_publisher');
const root=fs.mkdtempSync(path.join(os.tmpdir(),'mac-yakala-sharing-'));
const file=name=>path.join(root,name);
function authRequest(handler,{method='GET',url='/api/status',body={},cookie='',origin='https://panel.example',ip='one'}={}) {
    const req={path:url,method,ip,body,headers:{origin,host:'panel.example',cookie,'content-type':'application/json','x-mac-yakala-request':'1'}};
    const res={code:200,headers:{},status(n){this.code=n;return this;},setHeader(k,v){this.headers[k]=v;},json(data){this.data=data;return this;}};
    handler(req,res,()=>res.next=true);return res;
}
async function main(){
    let now=1000;
    const auth=createPanelAuth({password:'offline-test-password',now:()=>now,ttl:10000});
    assert.equal(authRequest(auth).code,401);
    assert.equal(authRequest(auth,{url:'/API/sharing-settings/'}).code,401);
    assert.equal(authRequest(auth,{url:'/api/sharing-settings',method:'POST',origin:'https://evil.example'}).code,403);
    assert.equal(authRequest(auth,{url:'/api/auth/login',method:'POST',body:{password:'wrong'}}).code,401);
    const logged=authRequest(auth,{url:'/api/auth/login',method:'POST',body:{password:'offline-test-password'}});
    assert.equal(logged.data.success,true);assert.match(logged.headers['Set-Cookie'],/HttpOnly; SameSite=Strict/);assert.match(logged.headers['Set-Cookie'],/Secure/);
    const cookie=logged.headers['Set-Cookie'].split(';')[0];
    assert.equal(authRequest(auth,{cookie}).next,true);
    assert.equal(authRequest(auth,{cookie,url:'/api/candidate-history/export'}).next,true);
    assert.equal(authRequest(auth,{url:'/statistics-coverage'}).code,401);
    assert.equal(authRequest(auth,{url:'/index.html'}).next,true);
    assert.equal(authRequest(auth,{cookie,method:'POST',url:'/api/auth/logout'}).data.success,true);
    assert.equal(authRequest(auth,{cookie}).code,401);
    const logged2=authRequest(auth,{url:'/api/auth/login',method:'POST',body:{password:'offline-test-password'}});
    now+=10001;assert.equal(authRequest(auth,{cookie:logged2.headers['Set-Cookie'].split(';')[0]}).code,401);
    const empty=createPanelAuth();assert.equal(authRequest(empty,{url:'/api/auth/login',method:'POST'}).code,503);
    for(let n=0;n<10;n++)authRequest(auth,{ip:'brute',url:'/api/auth/login',method:'POST'});
    assert.equal(authRequest(auth,{ip:'brute',url:'/api/auth/login',method:'POST',body:{password:'offline-test-password'}}).code,429);
    let ready=true;
    const settings=new SharingSettings({filePath:file('settings.json'),availability:()=>({extraTelegram:{configured:ready,reason:'missing'},x:{configured:ready,reason:'missing'}})});
    settings.load();assert.equal(settings.active('x'),false);assert.equal(settings.active('extraTelegram'),false);
    assert.throws(()=>settings.update({revision:0,x:'true'}));
    assert.throws(()=>settings.update({revision:0,apiKey:'secret'}));
    settings.update({revision:0,x:true,extraTelegram:true});assert.equal(settings.active('x'),true);
    assert.throws(()=>settings.update({revision:0,x:false}));
    const restored=new SharingSettings({filePath:file('settings.json'),availability:settings.availability});restored.load();assert.equal(restored.active('x'),true);
    const changedTarget=new SharingSettings({filePath:file('settings-copy.json'),availability:settings.availability,identities:()=>({extraTelegram:'new',x:'new'})});
    fs.copyFileSync(file('settings.json'),file('settings-copy.json'));changedTarget.load();assert.equal(changedTarget.active('x'),false);assert.equal(changedTarget.active('extraTelegram'),false);assert.equal(changedTarget.data.epochs.x,2);
    ready=false;assert.equal(settings.active('x'),false);assert.throws(()=>settings.update({revision:1,x:true}));ready=true;
    const tracker={data:{signals:[]},recordSent(p){if(!this.data.signals.some(s=>s.deliveryKey===p.deliveryKey))this.data.signals.push(p);}};
    const primaryCalls=[],extraCalls=[],xCalls=[];
    const primary=new TelegramDelivery({filePath:file('primary.json'),tracker,send:async(...args)=>{primaryCalls.push(args);return {message_id:100+primaryCalls.length,chat:{id:-1001}};}});primary.load();
    let extraId='-1002';
    const opts={filePath:file('mirrors.json'),settings,tracker,extraChatId:extraId,xIdentity:'fake-account',telegramSend:async(...args)=>{extraCalls.push(args);return {message_id:200+extraCalls.length,chat:{id:-1002}};},xSend:async r=>{xCalls.push(r);return {id:'123'};}};
    const mirror=new SharingDelivery(opts);mirror.load();
    const payload={fixtureId:1,signalType:'strong',signalSources:['V21'],sentAt:'2026-09-16T10:00:00Z',market:'1.5_UST',odds:1.65,minute:35,score:'0-0',match:'Test A - Test B',league:'Test ligi',statsValidation:{status:'passed'},analysis:'İki tarafın canlı verileri incelendi.'};
    assert.equal(await primary.publish('-1001',payload),true);
    const entry=primary.findSent('-1001',payload);await mirror.publish(entry);await mirror.publish(entry);
    assert.equal(extraCalls.length,1);assert.equal(xCalls.length,1);assert.equal(tracker.data.signals.length,1);
    assert.equal(primaryCalls[0][1],extraCalls[0][1]);assert.equal(extraCalls[0][1],formatSignal(payload));assert.equal(xCalls[0].minute,35);
    tracker.data.signals[0].settlement={result:'W'};
    await primary.flushWins();await mirror.flushWins();await mirror.flushWins();
    assert.equal(primaryCalls.length,2);assert.equal(extraCalls.length,2);assert.equal(xCalls.length,1);
    assert.equal(extraCalls[1][1],WIN_TEXT);assert.equal(JSON.parse(extraCalls[1][2].reply_parameters).message_id,201);
    assert.equal(JSON.parse(extraCalls[1][2].reply_parameters).allow_sending_without_reply,false);
    const second={...payload,signalSources:['V22'],minute:60,sentAt:'2026-09-16T10:25:00Z'};
    assert.equal(await primary.publish('-1001',second),true);await mirror.publish(primary.findSent('-1001',second));
    assert.equal(tracker.data.signals.length,2);assert.equal(xCalls.length,2);
    tracker.data.signals[1].settlement={result:'L'};await mirror.flushWins();assert.equal(extraCalls.length,3);
    const restart=new SharingDelivery(opts);restart.load();await restart.publish(entry);await restart.flushWins();assert.equal(extraCalls.length,3);
    tracker.data.signals[1].settlement={result:'W'};
    settings.update({revision:settings.data.revision,extraTelegram:false});await restart.flushWins();assert.equal(extraCalls.length,3);
    settings.update({revision:settings.data.revision,extraTelegram:true});await restart.flushWins();assert.equal(extraCalls.length,3,'off/on must not revive old wins');
    const missing=new SharingDelivery({...opts,extraChatId:''});missing.load();await missing.flushWins();assert.equal(extraCalls.length,3);
    const duplicate=new SharingDelivery({...opts,filePath:file('duplicate.json'),extraChatId:'-1001'});await duplicate.publish(entry);assert.equal(extraCalls.length,3);
    const failLogs=[];
    const failing=new SharingDelivery({...opts,filePath:file('fail.json'),logger:m=>failLogs.push(m),telegramSend:async()=>{throw {response:{body:{error_code:403}},secret:'do-not-log'};},xSend:async()=>{throw Error('secret-do-not-log');}});
    await failing.publish(entry);assert.deepEqual(failing.data.entries.map(e=>e.status),['declined','uncertain']);await failing.publish(entry);assert.equal(failing.data.entries.length,2);
    assert(!JSON.stringify(failLogs).includes('secret'));assert.equal(tracker.data.signals.length,2);
    const timeout=new SharingDelivery({...opts,filePath:file('timeout.json'),timeoutMs:5,telegramSend:()=>new Promise(()=>{}),xSend:()=>new Promise(()=>{})});await timeout.publish(entry);assert(timeout.data.entries.every(e=>e.status==='uncertain'));
    const interrupted=new SharingDelivery({...opts,filePath:file('interrupted.json')});
    interrupted.data={version:1,entries:[{key:'a',primaryKey:'p',kind:'extraTelegram',target:extraId,epoch:0,status:'sending',win:{status:'sending'}}]};interrupted.save();interrupted.load();assert.equal(interrupted.data.entries[0].status,'uncertain');assert.equal(interrupted.data.entries[0].win.status,'uncertain');
    fs.writeFileSync(file('broken.json'),'broken');const broken=new SharingDelivery({...opts,filePath:file('broken.json')});broken.load();assert.equal(broken.disabled,true);assert.equal(fs.readFileSync(file('broken.json'),'utf8'),'broken');
    // Official OAuth example values are intentionally invalid documentation credentials.
    const credentials={apiKey:'xvz1evFS4wEEPTGEFPHBog',apiSecret:'kAcSOqF21Fu85e7zjz7ZN2U4ZRhfV3WpwPAoE3Z7kBw',accessToken:'370773112-GmHxMAgYyLbNEtIKZeRNFsMKPR9EyMZeS9weJAEb',accessSecret:'LswwdoUaIvS8ltyTt5jkRh4J50vUPVVHtR2YPi5kE'};
    const header=oauthHeader({credentials,url:'https://api.x.com/1.1/statuses/update.json?include_entities=true',nonce:'kYjzVBB8Y0ZFabxSWbWovY3uYSQ2pTgmZeNu2VS4cg',timestamp:1318622958,form:{status:'Hello Ladies + Gentlemen, a signed OAuth request!'}});
    assert.match(header,/oauth_signature="Ls93hJiZbQ3akF3HF3x1Bz8%2FzU4%3D"/);
    let requestBody;
    const publish=createXPublisher({credentials,request:async r=>{requestBody=JSON.parse(r.body);return {statusCode:201,body:'{"data":{"id":"987"}}'};}});
    assert.deepEqual(await publish(payload),{id:'987'});assert.deepEqual(Object.keys(requestBody),['text']);assert.equal(requestBody.text,formatXSignal(payload));assert(!requestBody.text.includes('<b>'));assert(!requestBody.text.includes('YAKALADIK'));
    for(const code of [400,401,403,429,500]){
        const failed=createXPublisher({credentials,request:async()=>({statusCode:code,body:'secret-api-response'})});await assert.rejects(()=>failed(payload),e=>e.statusCode===code&&!e.message.includes('secret'));
    }
    await assert.rejects(()=>createXPublisher({credentials,request:async()=>({statusCode:201,body:'{}'})})(payload));
    const html=fs.readFileSync(path.join(__dirname,'public/index.html'),'utf8');
    assert.equal(html,fs.readFileSync(path.join(__dirname,'index.html'),'utf8'));assert(!html.includes('CORRECT_PASS'));assert(!html.includes('REMOTE_BACKEND_URL'));assert(html.includes('/api/auth/login'));assert(html.includes('/api/sharing-settings'));
    const nodes=new Map();
    const get=id=>{if(!nodes.has(id))nodes.set(id,{textContent:'',addEventListener(){},classList:{add(){},remove(){}}});return nodes.get(id);};
    const script=html.match(/<script>([\s\S]*?)<\/script>/)[1];
    const sandbox={window:{location:{origin:'http://127.0.0.1',protocol:'http:'}},document:{getElementById:get,querySelector:()=>null,querySelectorAll:()=>[],addEventListener(){}},setInterval(){},setTimeout(){},console,URLSearchParams,fetch:async()=>({ok:true,json:async()=>({})})};
    vm.createContext(sandbox);vm.runInContext(script,sandbox);
    sandbox.renderSharing({...settings.status(),delivery:mirror.status()});assert.equal(get('sharing-x').checked,true);assert.match(get('sharing-x-status').textContent,/Gönderildi/);
    let fetched;
    sandbox.fetch=async(url,options)=>{fetched={url,options};return {ok:true,json:async()=>({success:true})};};
    vm.runInContext('authenticated=true',sandbox);
    await sandbox.apiFetch('/api/start',{method:'POST'});
    assert.equal(fetched.options.body,'{}');assert.equal(fetched.options.headers['Content-Type'],'application/json');assert.equal(fetched.options.headers['X-Mac-Yakala-Request'],'1');
    sandbox.fetch=async()=>({ok:false,status:400,json:async()=>({error:'Disk hatası'})});
    await sandbox.saveSharing('x',false);assert.equal(get('sharing-x').checked,true,'Failed toggle must roll back');assert.match(get('sharing-message').textContent,/Disk hatası/);
    const server=fs.readFileSync(path.join(__dirname,'server.js'),'utf8');assert(server.indexOf('app.use(createPanelAuth')<server.indexOf('app.get('));assert(server.includes('sharingDelivery.publish(telegramDelivery.findSent'));assert.equal((server.match(/await sharingDelivery.flushWins\(\)/g)||[]).length,2);
    console.log('Sharing/auth/X tests OK: isolated fan-out, independent V21/V22, persistence, toggles, failures, win replies, OAuth, panel.');
}
main().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>fs.rmSync(root,{recursive:true,force:true}));
