'use strict';
const assert=require('assert/strict');
const {EventObservations,normalize}=require('./v23_events');
const at=m=>`2026-09-14T10:${String(m).padStart(2,'0')}:00.000Z`;
const event=(type,minute,detail='Normal Goal',player=9)=>({type,detail,time:{elapsed:minute,extra:null},team:{id:1},player:{id:player},assist:{id:2}});
const goal=event('Goal',50),store=new EventObservations({maxFixtures:2,maxSnapshots:4});
const mac=(m,events=[goal])=>({fixture_id:1,home_team_id:1,away_team_id:2,dakika:m,status_short:'2H',skor:'1-0',
    stats_received_at:at(m-1),_v23EventsAt:at(m-1),_v23Events:events,
    home_shot:5,away_shot:3,home_sot:2,away_sot:1,home_corner:2,away_corner:1,home_red:0,away_red:0});
let m=mac(51);store.capture(m,at(51));
assert.equal(store.evidence(m,at(51)).windows.goal.status,'insufficient','Cold start has no post-event interval');
m=mac(54);m.home_shot=7;m.home_sot=3;store.capture(m,at(54));
const good=store.evidence(m,at(54));assert.equal(good.scoreConsistent,true);assert.equal(good.windows.goal.status,'observed');
assert.equal(good.windows.goal.deltas.home.shot,2);assert.equal(good.windows.goal.tag,'SOT_OBSERVED');
assert.equal(good.windows.goal.event.firstObservedAt,at(50));
assert.equal(good.windows.goal.from.minute,51,'Do not invent exact statistics at event minute');
const frozen=JSON.stringify(good);
m=mac(55,[goal,event('Goal',55)]);m.skor='2-0';store.capture(m,at(55));
assert.equal(JSON.stringify(good),frozen,'Returned signal evidence is immutable by value');
assert.equal(store.evidence(m,at(55)).windows.goal.status,'insufficient');
assert.equal(store.evidence(m,at(53)).reason,'EVENTS_NOT_CAPTURED_AT_SIGNAL');
const stale=mac(56);stale._v23EventsAt=at(50);store.capture(stale,at(56));assert.equal(store.evidence(stale,at(56)).reason,'EVENTS_STALE_OR_FUTURE');
const future=mac(57);future._v23EventsAt=at(58);store.capture(future,at(57));assert.equal(store.evidence(future,at(57)).reason,'EVENTS_STALE_OR_FUTURE');
const missing=mac(58,null);store.capture(missing,at(58));assert.equal(store.evidence(missing,at(58)).status,'insufficient');
const malformed=mac(59,[{...goal,team:{id:999}}]);store.capture(malformed,at(59));assert.equal(store.evidence(malformed,at(59)).reason,'EVENT_IDENTITY_OR_TIME_INVALID');
const futureEvent=normalize([event('Goal',70)],mac(55),at(55));assert.equal(futureEvent.status,'insufficient');
const own=event('Goal',50,'Own Goal'),missed=event('Goal',51,'Missed Penalty'),cancelled=event('Goal',52,'Goal cancelled');
const second=new EventObservations();m=mac(54,[own,own,missed,cancelled,event('Var',53,'Goal cancelled')]);second.capture(m,at(54));
const ownResult=second.evidence(m,at(54));assert.equal(ownResult.validGoalCount,1);assert.equal(ownResult.events.length,4,'Identical event duplicates removed');assert.equal(ownResult.hasVar,true);
m=mac(55,[]);second.capture(m,at(55));assert.equal(second.evidence(m,at(55)).scoreConsistent,false,'Empty is not proof of zero goals');
const stoppage=normalize([{...goal,time:{elapsed:45,extra:4}}],mac(50),at(50));assert.equal(stoppage.events[0].phase,'1H');assert.equal(stoppage.events[0].extra,4);
const red=event('Card',50,'Red Card'),red2=event('Card',50,'Yellow-Red Card'),redStore=new EventObservations();m=mac(53,[goal,red,red2]);redStore.capture(m,at(53));
assert.equal(redStore.evidence(m,at(53)).redPlayerIds.length,1,'Second yellow and red are not two dismissals');
const corrected=new EventObservations();m=mac(51);corrected.capture(m,at(51));m=mac(54);m.home_shot=4;corrected.capture(m,at(54));
assert.equal(corrected.evidence(m,at(54)).windows.goal.reason,'STATS_MISSING_CORRECTED_OR_CARD_CHANGED');
const interrupted=new EventObservations();m=mac(51);interrupted.capture(m,at(51));m=mac(54,[goal,event('subst',52,'Substitution 1')]);interrupted.capture(m,at(54));
assert.equal(interrupted.evidence(m,at(54)).windows.goal.reason,'ANOTHER_EVENT_IN_WINDOW');
for(let id=1;id<=5;id++){m={...mac(55),fixture_id:id};store.capture(m,at(55));}assert.equal(store.entries.size,2);
assert.equal(store.metadata().additionalApiCalls,0);
const restarted=new EventObservations();assert.equal(restarted.evidence(mac(54),at(54)).status,'insufficient','Restart does not fabricate historic arrival times');
console.log('V23 events: as-known cutoffs, goal/card/sub windows, corrections, missing/stale/VAR/own goals, stoppage, dedup and bounded memory passed.');
